# Generated by Django 4.2.2 on 2023-06-17 18:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purpose", "0002_proposal_delete_purpose"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="cpf",
            field=models.BigIntegerField(),
        ),
    ]
